Insert Into estado (nome) Values('Acre');
Insert Into estado (nome) Values('Alagoas');
Insert Into estado (nome) Values('Amazonas');
Insert Into estado (nome) Values('Amapá');
Insert Into estado (nome) Values('Bahia');
Insert Into estado (nome) Values('Ceará');
Insert Into estado (nome) Values('Paraná');
Insert Into estado (nome) Values('Rio de Janeiro');
Insert Into estado (nome) Values('Rio Grande do Norte');
Insert Into estado (nome) Values('Rondônia');
Insert Into estado (nome) Values('Roraima');
Insert Into estado (nome) Values('Rio Grande do Sul');
Insert Into estado (nome) Values('Santa Catarina');
Insert Into estado (nome) Values('Sergipe');
Insert Into estado (nome) Values('São Paulo');
Insert Into estado (nome) Values('Tocantins');
Insert Into estado (nome) Values('Distrito Federal');
Insert Into estado (nome) Values('Espírito Santo');
Insert Into estado (nome) Values('Goiás');
Insert Into estado (nome) Values('Maranhão');
Insert Into estado (nome) Values('Minas Gerais');
Insert Into estado (nome) Values('Mato Grosso do Sul');
Insert Into estado (nome) Values('Mato Grosso');
Insert Into estado (nome) Values('Pará');
Insert Into estado (nome) Values('Paraíba');
Insert Into estado (nome) Values('Pernambuco');
Insert Into estado (nome) Values('Piauí');
